Rysard_Poplavskij
javaGuruBY/rpaS7 pull request #12
Opened 2021-04-12 19:13 UTC by RyszardP

First pull request

2021-04-13 15:23 UTC, PrinceVIS requested changes
Исправь англ. Калькулятор можно оставить как есть

2021-04-13 15:23 UTC, PrinceVIS commented on homework/java/RysardPoplavskij/lection1/algorithms.txt
> +*Наблюдать за птицами:
Наблюдать за птицами звучит интересно ;)

2021-04-13 15:23 UTC, PrinceVIS commented on homework/java/RysardPoplavskij/lection2/Addition.java
> +
Математические операции, думаю, лучше просто в методи класса MathOperationsDemo положить. Но для 1 раза так тоже пойдёт

2021-04-13 15:23 UTC, PrinceVIS commented on homework/english/RysardPoplavskij/lecture1/HW_lecture_1.md
> +4. I am Like tea, but today, I do not drinking it.
Тут правильнее будет I do like tea, but today, I am not drinking it, либо I don't like tea, but today, I am drinking it. Так получается потому что в первой части предложения твоё состояние (Pr.S.), а во второй - текущий статус(Pr.Cont.)

2021-04-13 16:06 UTC, RyszardP commented on homework/english/RysardPoplavskij/lecture1/HW_lecture_1.md
> +4. I am Like tea, but today, I do not drinking it.
исправил в коммите 6a7908e5c8e34333c2d6f2d8bada76b12592cf8f

2021-04-13 18:33 UTC, denhock commented on homework/english/RysardPoplavskij/lecture1/HW_lecture_1.md
> +4. I am Like tea, but today, I do not drinking it.
PrinceVIS. Только позитивное предложение без do. I like tea...сочетание do like не годится

2021-04-13 19:25 UTC, PrinceVIS commented on homework/english/RysardPoplavskij/lecture1/HW_lecture_1.md
> +4. I am Like tea, but today, I do not drinking it.
Это маленькое исключение https://hinative.com/ru/questions/63878

2021-04-13 19:28 UTC, PrinceVIS commented on homework/english/RysardPoplavskij/lecture1/HW_lecture_1.md
> +4. I am Like tea, but today, I do not drinking it.
Это маленькое исключение) https://hinative.com/ru/questions/63878

2021-04-13 19:29 UTC, PrinceVIS approved these changes
lgfm

2021-04-13 19:38 UTC, denhock commented on homework/english/RysardPoplavskij/lecture1/HW_lecture_1.md
> +4. I am Like tea, but today, I do not drinking it.
Прикольно, не встречал такого)

2021-04-13 19:58 UTC, sergey-ivanenko approved these changes

2021-04-13 20:14 UTC, denhock approved these changes

2021-04-14 07:33 UTC, GrandCkay requested changes
Насколько я понял, английский складывает в папку

2021-04-16 10:48 UTC, GrandCkay approved these changes

2021-04-16 10:48 UTC, merged