English homework1 has been done.
javaGuruBY/rpaS7 pull request #33
Opened 2021-04-16 19:15 UTC by sergey-ivanenko

2021-04-16 19:33 UTC, GrandCkay submitted a review, later dismissed

2021-04-16 21:11 UTC, denhock approved these changes, later dismissed

2021-04-17 09:58 UTC, danikkrapivnitskiy requested changes
see notes

2021-04-17 09:58 UTC, danikkrapivnitskiy commented on homework/english/sergey_ivanenko/homework1.md
> +2. Anyone who (smokes / is smoking) 20 cigarettes a day can expect to have health problems.
smokes "usually"
- [] add right answer

2021-04-17 13:01 UTC, sergey-ivanenko commented on homework/english/sergey_ivanenko/homework1.md
> +2. Anyone who (smokes / is smoking) 20 cigarettes a day can expect to have health problems.
done.

2021-04-17 14:23 UTC, GrandCkay approved these changes

2021-04-18 16:17 UTC, dk-t approved these changes

2021-04-20 08:20 UTC, danikkrapivnitskiy approved these changes
ftm

2021-04-22 07:37 UTC, closed without merging